[package]
name = "phobos"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
fst = "0.4.7" # !!
camino = "1.1.6"
time = "0.3.34"
binrw = "0.13.3"
fs-err = "2.11.0"
memmap2 = "0.9.4"

kdam = "0.5.1"
